app = "ai-similarity"  # Replace this with your unique Fly.io app name

[build]
  image = "python:3.12-slim"

[env]
  PORT = "5000"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
