name: Flask Gmail Checker

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the Flask app
      run: python main.py
      env:
        TOKEN_JSON: ${{ secrets.TOKEN_JSON }}  # ✅ This line is critical!


